version: "2"

services:
  dev:
    build: .
    depends_on:
      - aws-docker
    volumes:
      - .:/opt/local_s3

  aws-docker:
    container_name: my-tests.aws-docker
    image: atlassianlabs/localstack
    ports:
      - "4572:4572"
      - "8080:8080"
